### ISSUE TITLE
[Misconfiguration Log and Exit] Segfault because elementsd required by state recovery but unavailable

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#64]
`peerswap-plugin` restart while `lbtc` swap was in progress crashes with segmentation fault because it expects to be able to query `elementsd` but it is unavailable due to misconfiguration. PeerSwap should be able to recognize the contradiction, log the misconfiguration and exit gracefully instead of mysteriously segfault.  Note: It is otherwise valid for PeerSwap to start without `lbtc` swap support when swaps of that type were not already in progress.

**Low Priority**
Since this is misconfiguration handling this isn't a high priority bug. Might be a `good first issue` for a new contributor.

```
2022-05-31T05:22:34.970Z INFO    plugin-peerswap-plugin: [Swap:e2d5df28e680638875ede8474ffd04c207fb407f2d2fd68a9a427696abe67d68]: Recovering from state State_SwapInReceiver_AwaitTxConfirmation
```
`peerswap-plugin` would have logged something like this if `elementsd` was correctly configured. This was discovered by https://github.com/ElementsProject/lightning/issues/5294

```
$ journalctl -u lightning -f |grep peerswap
2022-05-31T02:27:30.401Z INFO    plugin-peerswap-plugin: cannot find liquid cookie file at /root/.elements/liquidv1/.cookie
2022-05-31T02:27:30.401Z INFO    plugin-peerswap-plugin: Error setting up liquid stat /root/.elements/liquidv1/.cookie: no such file or directory
2022-05-31T02:27:30.401Z INFO    plugin-peerswap-plugin: Liquid swaps disabled
2022-05-31T02:27:30.598Z INFO    plugin-peerswap-plugin: Bitcoin swaps enabled
2022-05-31T02:27:30.598Z INFO    plugin-peerswap-plugin: using policy:
2022-05-31T02:27:30.599Z INFO    plugin-peerswap-plugin: reserve_onchain_msat: 0
2022-05-31T02:27:30.599Z INFO    plugin-peerswap-plugin: allowlisted_peers: []
2022-05-31T02:27:30.599Z INFO    plugin-peerswap-plugin: accept_all_peers: false
2022-05-31T02:27:30.599Z INFO    plugin-peerswap-plugin:
2022-05-31T02:27:30.644Z INFO    plugin-peerswap-plugin: Killing plugin: exited during normal operation
```

Related: #56 `PeerSwap generally needs to know all error messages from CLN and LND to be able to distinguish fatal errors from expected temporary problems.`

version: 2833bdb8687f5c5b4337449bfb6546f028348ba7

**Comment by wtogami** [comment]
```
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x466a02 m=4 sigcode=128
signal arrived during cgo execution

goroutine 410033 [syscall]:
runtime.cgocall(0x706cf0, 0xc0004939f8)
	/usr/local/src/runtime/cgocall.go:157 +0x5c fp=0xc0004939d0 sp=0xc000493998 pc=0x4078bc
github.com/vulpemventures/go-secp256k1-zkp._Cfunc_secp256k1_context_create(0x301)
	_cgo_gotypes.go:298 +0x4d fp=0xc0004939f8 sp=0xc0004939d0 pc=0x6bd32d
github.com/vulpemventures/go-secp256k1-zkp.ContextCreate(0x301)
	/root/go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1.go:74 +0x37 fp=0xc000493a20 sp=0xc0004939f8 pc=0x6c1a77
github.com/vulpemventures/go-elements/confidential.nonceHash({0xc0000261b0, 0x21, 0x30}, {0xc000098b00, 0x20, 0x20})
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:175 +0x7b fp=0xc000493aa0 sp=0xc000493a20 pc=0x6c2e3b
github.com/vulpemventures/go-elements/confidential.NonceHash(...)
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:16
github.com/vulpemventures/go-elements/confidential.UnblindOutputWithKey(0xc0000d1050, {0xc000098b00?, 0x2?, 0xc00002aac0?})
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:39 +0x6a fp=0xc000493b40 sp=0xc000493aa0 pc=0x6c2cea
github.com/elementsproject/peerswap/onchain.(*LiquidOnChain).ValidateTx(0xc00006a300, 0xc0000760f0, {0xc000016a00, 0x23d6})
	/opt/plugins/ps/onchain/liquid.go:434 +0x112 fp=0xc000493bf8 sp=0xc000493b40 pc=0x6ceff2
github.com/elementsproject/peerswap/swap.(*ValidateTxAndPayClaimInvoiceAction).Execute(0xc0004e0070?, 0xc0001f01c0, 0xc00017a300)
	/opt/plugins/ps/swap/actions.go:642 +0xdb fp=0xc000493cf0 sp=0xc000493bf8 pc=0x6a1c9b
github.com/elementsproject/peerswap/swap.(*SwapStateMachine).SendEvent(0xc0004e0070, {0x7ac118, 0x13}, {0x0?, 0x0})
	/opt/plugins/ps/swap/fsm.go:187 +0x6f4 fp=0xc000493de0 sp=0xc000493cf0 pc=0x6a2c94
github.com/elementsproject/peerswap/swap.(*SwapService).OnTxConfirmed(0xc00014a000?, {0xc0002c2100?, 0x40?}, {0xc000016a00, 0x23d6})
	/opt/plugins/ps/swap/service.go:279 +0xa5 fp=0xc000493e68 sp=0xc000493de0 pc=0x6a73c5
github.com/elementsproject/peerswap/swap.(*SwapService).OnTxConfirmed-fm({0xc0002c2100?, 0xc00031e7b0?}, {0xc000016a00?, 0x40?})
	<autogenerated>:1 +0x3f fp=0xc000493ea0 sp=0xc000493e68 pc=0x6b519f
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).HandleConfirmedTx(0xc0000acd20, 0xc00045c0c0?)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:163 +0x1b0 fp=0xc000493f98 sp=0xc000493ea0 pc=0x6e89b0
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1.1()
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:96 +0x25 fp=0xc000493fe0 sp=0xc000493f98 pc=0x6e8445
runtime.goexit()
	/usr/local/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000493fe8 sp=0xc000493fe0 pc=0x466ba1
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:95 +0xe5

goroutine 1 [chan receive, 1063 minutes]:
main.run()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:259 +0x10e5
main.main()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:55 +0xe5

goroutine 6 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc0002890ce, 0xf32)
	/usr/local/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc0000ac000?, {0xc0002890ce?, 0x41b54b?, 0x7f8c15320400?})
	/usr/local/src/syscall/zsyscall_linux_amd64.go:696 +0x4d
syscall.Read(...)
	/usr/local/src/syscall/syscall_unix.go:188
internal/poll.ignoringEINTRIO(...)
	/usr/local/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0xc0000ac000?, {0xc0002890ce?, 0xf32?, 0xf32?})
	/usr/local/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/usr/local/src/os/file_posix.go:31
os.(*File).Read(0xc0000aa000, {0xc0002890ce?, 0xc00069bd88?, 0x46fa46?})
	/usr/local/src/os/file.go:119 +0x5e
bufio.(*Scanner).Scan(0xc00069be88)
	/usr/local/src/bufio/scan.go:215 +0x865
github.com/elementsproject/glightning/jrpc2.(*Server).listen(0xc0000ee240, {0x95d100?, 0xc0000aa000?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:108 +0xef
github.com/elementsproject/glightning/jrpc2.(*Server).StartUp(0xc0000ee240, 0xc0000eea00?, 0xc0000aa008)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:69 +0xa7
github.com/elementsproject/glightning/glightning.(*Plugin).Start(0xc0004e0000, 0x0?, 0x0?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1294 +0x149
github.com/elementsproject/peerswap/clightning.(*ClightningClient).Start(...)
	/opt/plugins/ps/clightning/clightning.go:210
main.run.func1()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:83 +0x3d
created by main.run
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:82 +0x13f

goroutine 7 [select, 1063 minutes]:
io.(*pipe).read(0xc0000ac480, {0xc000159000, 0x1000, 0x0?})
	/usr/local/src/io/pipe.go:57 +0xb1
io.(*PipeReader).Read(0x0?, {0xc000159000?, 0x0?, 0x0?})
	/usr/local/src/io/pipe.go:136 +0x25
bufio.(*Scanner).Scan(0xc000051f28)
	/usr/local/src/bufio/scan.go:215 +0x865
github.com/elementsproject/glightning/glightning.(*Plugin).checkForMonkeyPatch.func1({0x95cde0?, 0xc0000100c0?}, 0xc0004e0000)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1327 +0xaf
created by github.com/elementsproject/glightning/glightning.(*Plugin).checkForMonkeyPatch
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1324 +0x27b

goroutine 8 [chan receive]:
github.com/elementsproject/glightning/jrpc2.(*Server).setupWriteQueue(0xc0000ee240, {0x95d120?, 0xc0000aa008?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:132 +0x125
created by github.com/elementsproject/glightning/jrpc2.(*Server).StartUp
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:68 +0x91

goroutine 20 [chan receive]:
github.com/elementsproject/glightning/jrpc2.(*Client).setupWriteQueue(0xc0000ae050, {0x7f8c150f82d8?, 0xc0000aa040?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:91 +0x165
github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart(0xc0000ae050, {0xc0000b6690, 0x26}, 0xc000080420)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:64 +0x1c5
github.com/elementsproject/glightning/glightning.(*Lightning).StartUp.func1(0xc000091140, {0xc00009a350?, 0x665192?}, {0xc0000cc258?, 0xc0000f8800?}, 0x3c8?, 0x3c8?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/lightning.go:34 +0x85
created by github.com/elementsproject/glightning/glightning.(*Lightning).StartUp
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/lightning.go:33 +0x165

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f8c150837d8, 0x72)
	/usr/local/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000092400?, 0xc0003c0002?, 0x0)
	/usr/local/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000092400, {0xc0003c0002, 0x7fdfe, 0x7fdfe})
	/usr/local/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000092400, {0xc0003c0002?, 0xc00031ee10?, 0x203000?})
	/usr/local/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000aa040, {0xc0003c0002?, 0xc0003c0000?, 0xc000495ee0?})
	/usr/local/src/net/net.go:183 +0x45
encoding/json.(*Decoder).refill(0xc0000fe280)
	/usr/local/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc0000fe280)
	/usr/local/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc0000fe280, {0x74d9c0, 0xc0003521b0})
	/usr/local/src/encoding/json/stream.go:63 +0x78
github.com/elementsproject/glightning/jrpc2.(*Client).readQueue(0xc0000ae050, {0x95cf20?, 0xc0000aa040})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:113 +0xab
github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart.func1({0x960678?, 0xc0000aa040}, 0x3c8?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:62 +0x6b
created by github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:58 +0x19e

goroutine 44 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1()
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:107 +0x135
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:86 +0x15b

goroutine 43 [select]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartBlockWatcher(0xc00006cba0, 0xb44c5)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:120 +0xf6
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:85 +0xc9

goroutine 41 [select]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartBlockWatcher(0xc0000acd20, 0x1c4eb6)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:120 +0xf6
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:85 +0xc9

goroutine 42 [semacquire]:
sync.runtime_SemacquireMutex(0x44a1fa?, 0xa0?, 0xc000457c20?)
	/usr/local/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0000acd70)
	/usr/local/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/src/sync/mutex.go:81
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).HandleCsvTx(0xc0000acd20, 0x1c52de?)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:179 +0x52
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1()
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:102 +0xf4
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:86 +0x15b

goroutine 409371 [select, 2 minutes]:
github.com/elementsproject/peerswap/timer.TimedCallback({0x95f870, 0xc000444ac0}, 0x635?, 0xc000184ac0)
	/opt/plugins/ps/timer/timer.go:11 +0x8e
created by github.com/elementsproject/peerswap/swap.(*timeOutService).addNewTimeOut
	/opt/plugins/ps/swap/timeout.go:22 +0xb9

goroutine 214 [select, 43 minutes]:
github.com/elementsproject/peerswap/poll.(*Service).Start.func1()
	/opt/plugins/ps/poll/service.go:89 +0xa5
created by github.com/elementsproject/peerswap/poll.(*Service).Start
	/opt/plugins/ps/poll/service.go:87 +0x5b

goroutine 409985 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect.func1()
	/opt/plugins/ps/clightning/clightning.go:427 +0x35
created by github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect
	/opt/plugins/ps/clightning/clightning.go:425 +0x72

rax    0x17
rbx    0x7ae5d0
rcx    0x4683d5
rdx    0x17
rdi    0x2
rsi    0x7ae5d0
rbp    0x5de5
rsp    0x7f8c151822e8
r8     0x625295ed0
r9     0x54b451c2dd668
r10    0x38b0684
r11    0x246
r12    0x1311edb5f1895b
r13    0xdd84880
r14    0xc000003520
r15    0xcfdfcc60
rip    0x466a02
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e8034]

goroutine 1 [running]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).GetBlockHeight(0x1?)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:55 +0x14
github.com/elementsproject/peerswap/swap.(*AwaitTxConfirmationAction).Execute(0xc000210e20?, 0xc000076380, 0xc000219200)
	/opt/plugins/ps/swap/actions.go:600 +0x9b
github.com/elementsproject/peerswap/swap.StopSendMessageWithRetryWrapperAction.Execute({{0x95c9a0?, 0xb872e0?}}, 0xc000076380, 0xc000219200)
	/opt/plugins/ps/swap/actions.go:260 +0xd0
github.com/elementsproject/peerswap/swap.(*SwapStateMachine).Recover(0xc0001f6a80)
	/opt/plugins/ps/swap/fsm.go:230 +0x1ab
github.com/elementsproject/peerswap/swap.(*SwapService).RecoverSwaps(0xc0002038f0)
	/opt/plugins/ps/swap/service.go:120 +0x4c5
main.run()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:253 +0x107b
main.main()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:55 +0xe5
```

**Comment by wtogami** [comment]
Unable to reproduce anymore.
