### ISSUE TITLE
CLN: peerswap-plugin crash after peer failed to pay swap invoice

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#73]
CLN v0.10.2 PeerSwap 2833bdb8687f5c5b4337449bfb6546f028348ba7
LND v0.14.1-beta PeerSwap 1f0e91fe95b5e8124d035628cb91623fea462b50

LND requested lbtc swap-out from CLN. Swap payment failed to find a route and we know it was the LND node's fault. How?

https://github.com/accumulator/charge-lnd
* They were running charge-lnd which had dropped max_htlc to 1 as part of an automated forwarding discouragement strategy for an imbalanced channel.
* They had ~200k sats on their side so they thought they would do a 100k sats `swap-out` test. They forgot about charge-lnd.
* Since the maximum htlc size is set to 1 sat the fee prepayment invoice was paid via an unrelated route. See: #61 where I argued fee prepayments should be explicitly over the same channel partly as a sanity check.
* The swap payment fails to find a route which is expected in this weird scenario.
* The unexpected part is it causes CLN peerswap-plugin to crash.

```
2022-06-03T08:40:42.487Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_OnSwapOutRequestReceived on
2022-06-03T08:40:42.749Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_ActionSucceeded on State_SwapOutReceiver_CreateSwap
2022-06-03T08:40:42.749Z INFO    plugin-peerswap-plugin: [Swap:6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560] swap out request received: peer: REDACTEDLNDPUBKEY chanId: REDACTEDHEIGHT:REDACTEDINDEX:1 initiator: REDACTEDLNDPUBKEY amount 100000
2022-06-03T08:40:42.752Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_ActionSucceeded on State_SwapOutReceiver_SendFeeInvoice
2022-06-03T08:40:43.895Z INFO    lightningd: Resolved invoice '6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560_fee' with amount 258000msat in 1 htlcs
2022-06-03T08:40:43.902Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_OnFeeInvoicePaid on State_SwapOutReceiver_AwaitFeeInvoicePayment
2022-06-03T08:40:45.369Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_ActionSucceeded on State_SwapOutReceiver_BroadcastOpeningTx
2022-06-03T08:40:45.369Z DEBUG   plugin-peerswap-plugin: [RedundantSender]\tstart sending messages of type 42077 to REDACTEDLNDPUBKEY
2022-06-03T08:40:45.369Z DEBUG   plugin-peerswap-plugin:
2022-06-03T08:40:45.372Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_ActionSucceeded on State_SwapOutReceiver_SendTxBroadcastedMessage
2022-06-03T08:44:36.676Z DEBUG   plugin-peerswap-plugin: [Messenger] From: REDACTEDLNDPUBKEY got msgtype: a461 payload: {\"swap_id\":\"6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560\",\"message\":\"could not pay invoice, last err payment failure FAILURE_REASON_NO_ROUTE\",\"privkey\":\"cf22815b60f825e73c0cecd932232f28459e4da207e4eab47fb8eb7a748ba456\"}
2022-06-03T08:44:36.689Z DEBUG   plugin-peerswap-plugin: [FSM] event:id: 6a0fbd775103b48e08ac7bf3e873637cc539442ee1a64d05710fcc62e4a37560, Event_OnCoopCloseReceived on State_SwapOutReceiver_AwaitClaimInvoicePayment
2022-06-03T08:44:36.689Z DEBUG   plugin-peerswap-plugin: [RedundantSender]\tstop sending messages of type 42077 to REDACTEDLNDPUBKEY
2022-06-03T08:44:36.689Z DEBUG   plugin-peerswap-plugin:
2022-06-03T08:44:37.236Z INFO    plugin-peerswap-plugin: Killing plugin: exited during normal operation
```

peerswap-panic-log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e8034]

goroutine 1 [running]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).GetBlockHeight(0x1?)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:55 +0x14
github.com/elementsproject/peerswap/swap.(*AwaitTxConfirmationAction).Execute(0xc000210e20?, 0xc000076380, 0xc000219200)
	/opt/plugins/ps/swap/actions.go:600 +0x9b
github.com/elementsproject/peerswap/swap.StopSendMessageWithRetryWrapperAction.Execute({{0x95c9a0?, 0xb872e0?}}, 0xc000076380, 0xc000219200)
	/opt/plugins/ps/swap/actions.go:260 +0xd0
github.com/elementsproject/peerswap/swap.(*SwapStateMachine).Recover(0xc0001f6a80)
	/opt/plugins/ps/swap/fsm.go:230 +0x1ab
github.com/elementsproject/peerswap/swap.(*SwapService).RecoverSwaps(0xc0002038f0)
	/opt/plugins/ps/swap/service.go:120 +0x4c5
main.run()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:253 +0x107b
main.main()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:55 +0xe5
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x466a02 m=4 sigcode=128
signal arrived during cgo execution

goroutine 1057002 [syscall]:
runtime.cgocall(0x706cf0, 0xc000619238)
	/usr/local/src/runtime/cgocall.go:157 +0x5c fp=0xc000619210 sp=0xc0006191d8 pc=0x4078bc
github.com/vulpemventures/go-secp256k1-zkp._Cfunc_secp256k1_context_create(0x301)
	_cgo_gotypes.go:298 +0x4d fp=0xc000619238 sp=0xc000619210 pc=0x6bd32d
github.com/vulpemventures/go-secp256k1-zkp.ContextCreate(0x301)
	/root/go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1.go:74 +0x37 fp=0xc000619260 sp=0xc000619238 pc=0x6c1a77
github.com/vulpemventures/go-elements/confidential.nonceHash({0xc0002b2210, 0x21, 0x30}, {0xc000476a20, 0x20, 0x20})
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:175 +0x7b fp=0xc0006192e0 sp=0xc000619260 pc=0x6c2e3b
github.com/vulpemventures/go-elements/confidential.NonceHash(...)
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:16
github.com/vulpemventures/go-elements/confidential.UnblindOutputWithKey(0xc000490e10, {0xc000476a20?, 0x3?, 0x13d6e81?})
	/root/go/pkg/mod/github.com/vulpemventures/go-elements@v0.3.7/confidential/confidential.go:39 +0x6a fp=0xc000619380 sp=0xc0006192e0 pc=0x6c2cea
github.com/elementsproject/peerswap/onchain.(*LiquidOnChain).createSpendingTransaction(0xc0000ee5c0, {0xc000370800, 0x45f4}, 0x186a0, 0x0, {0xc0000b64b0, 0x21, 0x30}, {0xc000654400, 0x98, ...}, ...)
	/opt/plugins/ps/onchain/liquid.go:273 +0x230 fp=0xc0006198e0 sp=0xc000619380 pc=0x6cd870
github.com/elementsproject/peerswap/onchain.(*LiquidOnChain).CreateCoopSpendingTransaction(0xc0000ee5c0, 0xc000076280, 0xc00009c2a0, {0x95bea0, 0xc0004e22a0})
	/opt/plugins/ps/onchain/liquid.go:197 +0x225 fp=0xc000619ad0 sp=0xc0006198e0 pc=0x6cca85
github.com/elementsproject/peerswap/swap.(*ClaimSwapTransactionCoop).Execute(0xc0001b9470?, 0xc0005f5600?, 0xc0001a4480)
	/opt/plugins/ps/swap/actions.go:443 +0x149 fp=0xc000619b50 sp=0xc000619ad0 pc=0x6a0749
github.com/elementsproject/peerswap/swap.StopSendMessageWithRetryWrapperAction.Execute({{0x95ca20?, 0xb872e0?}}, 0xc000164380, 0xc0001a4480)
	/opt/plugins/ps/swap/actions.go:260 +0xd0 fp=0xc000619b90 sp=0xc000619b50 pc=0x69f0d0
github.com/elementsproject/peerswap/swap.(*StopSendMessageWithRetryWrapperAction).Execute(0xc00009c070?, 0xc000457e00?, 0x7b53df?)
	<autogenerated>:1 +0x3d fp=0xc000619bc0 sp=0xc000619b90 pc=0x6b58dd
github.com/elementsproject/peerswap/swap.(*SwapStateMachine).SendEvent(0xc00009c070, {0x7af4a1, 0x19}, {0x95e438?, 0xc00046dfb0})
	/opt/plugins/ps/swap/fsm.go:187 +0x6f4 fp=0xc000619cb0 sp=0xc000619bc0 pc=0x6a2c94
github.com/elementsproject/peerswap/swap.(*SwapService).OnCoopCloseReceived(0xc000184000?, 0xc000099380?, 0x42?)
	/opt/plugins/ps/swap/service.go:611 +0xa5 fp=0xc000619d48 sp=0xc000619cb0 pc=0x6a9be5
github.com/elementsproject/peerswap/swap.(*SwapService).OnMessageReceived(0xc00004fe10?, {0xc00029bcc0, 0x42}, {0xc000178600, 0x4}, {0xc000184000, 0xef, 0x1e0})
	/opt/plugins/ps/swap/service.go:263 +0x64c fp=0xc000619dd0 sp=0xc000619d48 pc=0x6a712c
github.com/elementsproject/peerswap/swap.(*SwapService).OnMessageReceived-fm({0xc00029bcc0?, 0xc000178604?}, {0xc000178600?, 0xc000184000?}, {0xc000184000?, 0x72a8e0?, 0xc00062c040?})
	<autogenerated>:1 +0x59 fp=0xc000619e20 sp=0xc000619dd0 pc=0x6b50d9
github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnCustomMsg(0xc000068000, 0xc00046df20)
	/opt/plugins/ps/clightning/clightning.go:236 +0x1cf fp=0xc000619ec0 sp=0xc000619e20 pc=0x6dcd8f
github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnCustomMsg-fm(0x7f54939b8108?)
	<autogenerated>:1 +0x2c fp=0xc000619ee0 sp=0xc000619ec0 pc=0x6e706c
github.com/elementsproject/glightning/glightning.(*CustomMsgReceivedEvent).Call(0xc0000aa3d8?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:68 +0x1d fp=0xc000619ef8 sp=0xc000619ee0 pc=0x670bbd
github.com/elementsproject/glightning/jrpc2.Execute(0xc00044d410, {0x95eee0?, 0xc00046df20?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:196 +0x30 fp=0xc000619f48 sp=0xc000619ef8 pc=0x6657f0
github.com/elementsproject/glightning/jrpc2.processMsg(0xc00006a080, {0xc000633600, 0x526, 0x526})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:192 +0x165 fp=0xc000619fb0 sp=0xc000619f48 pc=0x6655c5
github.com/elementsproject/glightning/jrpc2.(*Server).listen.func1()
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:120 +0x32 fp=0xc000619fe0 sp=0xc000619fb0 pc=0x665192
runtime.goexit()
	/usr/local/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000619fe8 sp=0xc000619fe0 pc=0x466ba1
created by github.com/elementsproject/glightning/jrpc2.(*Server).listen
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:120 +0xe5

goroutine 1 [chan receive, 2741 minutes]:
main.run()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:259 +0x10e5
main.main()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:55 +0xe5

goroutine 21 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc000250000, 0x800)
	/usr/local/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc0000ac000?, {0xc000250000?, 0x41b54b?, 0x7f546ceb8700?})
	/usr/local/src/syscall/zsyscall_linux_amd64.go:696 +0x4d
syscall.Read(...)
	/usr/local/src/syscall/syscall_unix.go:188
internal/poll.ignoringEINTRIO(...)
	/usr/local/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0xc0000ac000?, {0xc000250000?, 0x800?, 0x800?})
	/usr/local/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/usr/local/src/os/file_posix.go:31
os.(*File).Read(0xc0000aa000, {0xc000250000?, 0xc000054d88?, 0x46fa46?})
	/usr/local/src/os/file.go:119 +0x5e
bufio.(*Scanner).Scan(0xc000054e88)
	/usr/local/src/bufio/scan.go:215 +0x865
github.com/elementsproject/glightning/jrpc2.(*Server).listen(0xc00006a080, {0x95d100?, 0xc0000aa000?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:108 +0xef
github.com/elementsproject/glightning/jrpc2.(*Server).StartUp(0xc00006a080, 0xc0000ee240?, 0xc0000aa008)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:69 +0xa7
github.com/elementsproject/glightning/glightning.(*Plugin).Start(0xc00009c000, 0x0?, 0x0?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1294 +0x149
github.com/elementsproject/peerswap/clightning.(*ClightningClient).Start(...)
	/opt/plugins/ps/clightning/clightning.go:210
main.run.func1()
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:83 +0x3d
created by main.run
	/opt/plugins/ps/cmd/peerswap-plugin/main.go:82 +0x13f

goroutine 5 [select, 2741 minutes]:
io.(*pipe).read(0xc0000ac240, {0xc0000fc000, 0x1000, 0x1?})
	/usr/local/src/io/pipe.go:57 +0xb1
io.(*PipeReader).Read(0x0?, {0xc0000fc000?, 0x0?, 0x0?})
	/usr/local/src/io/pipe.go:136 +0x25
bufio.(*Scanner).Scan(0xc00004ef28)
	/usr/local/src/bufio/scan.go:215 +0x865
github.com/elementsproject/glightning/glightning.(*Plugin).checkForMonkeyPatch.func1({0x95cde0?, 0xc0000aa018?}, 0xc00009c000)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1327 +0xaf
created by github.com/elementsproject/glightning/glightning.(*Plugin).checkForMonkeyPatch
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/plugin.go:1324 +0x27b

goroutine 6 [chan receive]:
github.com/elementsproject/glightning/jrpc2.(*Server).setupWriteQueue(0xc00006a080, {0x95d120?, 0xc0000aa008?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:132 +0x125
created by github.com/elementsproject/glightning/jrpc2.(*Server).StartUp
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/server.go:68 +0x91

goroutine 42 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1()
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:107 +0x135
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:86 +0x15b

goroutine 9 [chan receive]:
github.com/elementsproject/glightning/jrpc2.(*Client).setupWriteQueue(0xc000076050, {0x7f546cbbbe38?, 0xc0000aa060?})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:91 +0x165
github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart(0xc000076050, {0xc0000b6450, 0x26}, 0xc0004cc180)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:64 +0x1c5
github.com/elementsproject/glightning/glightning.(*Lightning).StartUp.func1(0xc000020300, {0xc00009a350?, 0x665192?}, {0xc0000cc108?, 0xc0000f8800?}, 0x3ac?, 0x3ac?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/lightning.go:34 +0x85
created by github.com/elementsproject/glightning/glightning.(*Lightning).StartUp
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/lightning.go:33 +0x165

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f546cbf38d8, 0x72)
	/usr/local/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000092180?, 0xc0003b4002?, 0x0)
	/usr/local/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000092180, {0xc0003b4002, 0x7fdfe, 0x7fdfe})
	/usr/local/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000092180, {0xc0003b4002?, 0xc00046d800?, 0x203000?})
	/usr/local/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000aa060, {0xc0003b4002?, 0xc0003b4000?, 0xc0002edee0?})
	/usr/local/src/net/net.go:183 +0x45
encoding/json.(*Decoder).refill(0xc0004f2000)
	/usr/local/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc0004f2000)
	/usr/local/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc0004f2000, {0x74d9c0, 0xc00028ecf0})
	/usr/local/src/encoding/json/stream.go:63 +0x78
github.com/elementsproject/glightning/jrpc2.(*Client).readQueue(0xc000076050, {0x95cf20?, 0xc0000aa060})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:113 +0xab
github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart.func1({0x960678?, 0xc0000aa060}, 0x3ac?)
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:62 +0x6b
created by github.com/elementsproject/glightning/jrpc2.(*Client).SocketStart
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:58 +0x19e

goroutine 41 [select]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartBlockWatcher(0xc00006d2c0, 0xb4622)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:120 +0xf6
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:85 +0xc9

goroutine 39 [select]:
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartBlockWatcher(0xc00006ccc0, 0x1c5c27)
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:120 +0xf6
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:85 +0xc9

goroutine 40 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs.func1()
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:107 +0x135
created by github.com/elementsproject/peerswap/txwatcher.(*BlockchainRpcTxWatcher).StartWatchingTxs
	/opt/plugins/ps/txwatcher/rpctxwatcher.go:86 +0x15b

goroutine 1056926 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect.func1()
	/opt/plugins/ps/clightning/clightning.go:427 +0x35
created by github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect
	/opt/plugins/ps/clightning/clightning.go:425 +0x72

goroutine 1055396 [select, 3 minutes]:
github.com/elementsproject/peerswap/timer.TimedCallback({0x95f870, 0xc000434040}, 0xc000076050?, 0xc0004bc0a0)
	/opt/plugins/ps/timer/timer.go:11 +0x8e
created by github.com/elementsproject/peerswap/swap.(*timeOutService).addNewTimeOut
	/opt/plugins/ps/swap/timeout.go:22 +0xb9

goroutine 1055459 [chan receive, 3 minutes]:
github.com/elementsproject/glightning/jrpc2.(*Client).RequestNoTimeout(0xc000076050, {0x95c820?, 0xc0002cace0}, {0x728760, 0xc0004b9450})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/jrpc2/client.go:199 +0x18d
github.com/elementsproject/glightning/glightning.(*Lightning).WaitInvoice(0xc000020300, {0xc0001f10e0, 0x46})
	/root/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20220502095901-74f998c51367/glightning/lightning.go:694 +0xa5
github.com/elementsproject/peerswap/clightning.(*ClightningClient).AddPaymentNotifier.func1()
	/opt/plugins/ps/clightning/clightning.go:99 +0x110
created by github.com/elementsproject/peerswap/clightning.(*ClightningClient).AddPaymentNotifier
	/opt/plugins/ps/clightning/clightning.go:93 +0x1c5

goroutine 216 [select, 41 minutes]:
github.com/elementsproject/peerswap/poll.(*Service).Start.func1()
	/opt/plugins/ps/poll/service.go:89 +0xa5
created by github.com/elementsproject/peerswap/poll.(*Service).Start
	/opt/plugins/ps/poll/service.go:87 +0x5b

goroutine 1056975 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/src/runtime/time.go:194 +0x12e
github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect.func1()
	/opt/plugins/ps/clightning/clightning.go:427 +0x35
created by github.com/elementsproject/peerswap/clightning.(*ClightningClient).OnConnect
	/opt/plugins/ps/clightning/clightning.go:425 +0x72

rax    0x17
rbx    0x7ae5d0
rcx    0x4683d5
rdx    0x17
rdi    0x2
rsi    0x7ae5d0
rbp    0x5de5
rsp    0x7f546ccec2e8
r8     0x625295ed0
r9     0x54b451c2dd668
r10    0x38b0684
r11    0x246
r12    0x1311edb5f1895b
r13    0xdd84880
r14    0xc000003520
r15    0xcfdfcc60
rip    0x466a02
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by nepet** [comment]
@wtogami since 6135d8dd2898310d1bd1a135e8447fed50e9d464 we have a nil check to at least avoid a panic.
Maybe we can close this for now, we still have it documented here and can reopen in the case that this happens again or if we have a better solution at some point.
